# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\"\x16\n\x07Request\x12\x0b\n\x03Url\x18\x01 \x01(\t\"\x1e\n\x0bTextRequest\x12\x0f\n\x07\x43ontent\x18\x01 \x01(\t\"\x19\n\x05Reply\x12\x10\n\x08jsonData\x18\x01 \x01(\t2V\n\tImgHandle\x12!\n\x0bImgToVector\x12\x08.Request\x1a\x06.Reply\"\x00\x12&\n\x0cTextToVector\x12\x0c.TextRequest\x1a\x06.Reply\"\x00\x42\x07Z\x05../pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005../pb'
  _REQUEST._serialized_start=15
  _REQUEST._serialized_end=37
  _TEXTREQUEST._serialized_start=39
  _TEXTREQUEST._serialized_end=69
  _REPLY._serialized_start=71
  _REPLY._serialized_end=96
  _IMGHANDLE._serialized_start=98
  _IMGHANDLE._serialized_end=184
# @@protoc_insertion_point(module_scope)
